import streamlit as st

def app():
    st.title("Details")
    st.write('**How to Use RipScan to Stay Safe in the Water**')
    st.write('We’ve made it super easy to check the water conditions before you dive in! Here’s how to use our app:')
    st.write('**Step 1: Snap a Picture of the Water**')
    st.write('Before you head in, take a quick picture of the water you’re about to swim in using your phone’s camera. Try to capture a clear view of the waves, shoreline, and overall conditions.')
    st.write('**Step 2: Let the App Work Its Magic**')
    st.write('Once you upload the photo, our app uses machine learning to analyze the water conditions. It looks for signs of rip currents, debris, and other possible hazards to help you stay safe.')
    st.write('**Step 3: Get an Instant Safety Check**')
    st.write('Within seconds, the app will tell you if it’s safe to go in or not. You’ll get helpful tips, like how to identify rip currents and what to do if you’re caught in one.')
    st.write('**Step 4: Enjoy Your Swim!**')
    st.write('If the water’s safe, dive in and have fun! Just remember to swim near lifeguards and keep an eye on any changes in the water.')
    st.write('**Stay Safe, Stay Informed**')
    st.write('RipScan is here to make sure your beach day stays fun and worry-free. Whether you are an experienced swimmer or just enjoying a quick dip, you will always know what is in the water befire you go in')
    st.write('______________')
    st.write('**What Exactly is a Rip Current?**')
    st.write('A rip current is like a sneaky river that pulls water out to sea. It’s powerful, narrow, and can surprise you when you least expect it. Rip currents form when water that’s pushed toward the shore has to find its way back to the ocean, creating fast-moving streams.')
    st.image('ripcurrents1.png')
    st.write('**How Can You Spot a Rip Current?**')
    st.write('**Look for Color Changes:**')
    st.write('Rip currents usually look darker because they’re deeper than the surrounding water. If you notice a patch of calm, dark water cutting through breaking waves, it might be a rip current.')
    st.write('**Strange Looking Water:**')
    st.write('Water in a rip current can look choppy or foamy and doesn’t follow the same pattern as the surrounding waves.')
    st.write('**No Waves:**')
    st.write('If you see a section of water without breaking waves, while everywhere else has them, a rip current might be flowing there.')
    st.write('**Floating Debris Moving Seaward:**')
    st.write('If you notice things like seaweed or foam moving rapidly away from shore in a straight path, that is another sign of a rip current.')
    st.image('ripcurrents2.png')
    st.write('**What to Do if You’re Caught in a Rip Current:**')
    st.write('**1. Stay Calm and Float:**')
    st.write('Don’t panic! A rip current doesn’t drag you underwater, it just pulls you away from shore.')
    st.write('**2. Don’t Fight It:**')
    st.write('Swimming straight back to shore against a rip current is exhausting. Instead, swim parallel to the shore to escape the narrow current.')
    st.write('**3. Float and Signal for Help:**')
    st.write('If you’re too tired to swim, float on your back or tread water and wave your arms to signal for help.')
    st.write('**4. Once You’re Out, Swim at an Angle Back to Shore:**')
    st.write('After you escape the rip current, swim diagonally back to the beach to avoid getting pulled in again')
    st.image('ripcurrents3.png')
    st.write('**How to Help Someone Else:**')
    st.write('**Don’t Jump In!**')
    st.write('Instead of swimming out, throw them something that floats, like a life preserver or a board. Alert a lifeguard or call for help immediately.')
    st.write('**Stay Safe Yourself:**')
    st.write('If you’re not a trained rescuer, it’s better to stay on the shore and get help from the professionals.')
    st.write('__________')
    st.write('**The Dangers of Rip Currents:**')
    st.write('**What You Need to Know**')
    st.write('Rip currents are one of the deadliest dangers at the beach. Even if they’re hard to spot, their impact is undeniable. Here are some key facts and figures that show why it’s important to understand the risks.')
    st.write('**Why Are Rip Currents Dangerous?**')
    st.write('**They’re Incredibly Powerful:**')
    st.write('Rip currents can flow at speeds of 1 to 2 feet per second, but stronger ones can reach up to 8 feet per second. To put that in perspective, that’s faster than most people can swim, no matter how strong a swimmer they are.')
    st.write('**They Can Form Quickly:**')
    st.write('Rip currents can form in minutes, especially after large waves break on the shore. Even on calm or seemingly safe days, they can develop unexpectedly and pose a serious threat.')
    st.write('**Statistics Show How Serious They Are**')
    st.write('**80 percent of Beach Rescues Involve Rip Currents**')
    st.write('According to the United States Lifesaving Association (USLA), rip currents account for 80 percent of all beach rescues. That’s how common they are!')
    st.write('**About 100 People Die from Rip Currents Every Year in the U.S.:**')
    st.write('Rip currents are responsible for around 100 fatalities annually. Globally, they contribute to many more drownings, as they are present on most beaches with breaking waves.')
    st.write('**Nearly 70 percent of Americans Don’t Know What a Rip Current Is**')
    st.write('A study by the National Oceanic and Atmospheric Administration (NOAA) found that about 70 percent of Americans don’t fully understand the risks associated with rip currents or how to escape one.')
    st.write('**Rip Currents Can Stretch Over 50 Yards Wide:**')
    st.write('They often cover large areas of the beach and can pull swimmers hundreds of feet away from shore in minutes')
    st.write('**The Bottom Line:**')
    st.write('Rip currents are responsible for a large percentage of beach drownings and rescues worldwide. By understanding the dangers and knowing how to react, you can enjoy the ocean safely. Always swim in guarded areas, learn to spot rip currents, and remember that even on the calmest beach days, they can strike without warning.')

